{% set version = "2.44.1" %}

package:
  name: graphviz
  version: {{ version }}

source:
  url: https://www2.graphviz.org/Packages/stable/portable_source/graphviz-{{ version }}.tar.gz  # [unix]
  md5: 96792adafea5cc6879060c400da31ea3  # [unix]

  url: https://www2.graphviz.org/Packages/stable/windows/10/cmake/Release/x64/graphviz-{{ version }}-win64.exe  # [win]
  md5: ff2f81e20c1982f5f97fbf7166ecf751  # [win]

build:
  number: 3
  detect_binary_files_with_prefix: true  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config               # [osx]
    - make                     # [unix]
  host:
    - cairo                    # [linux]
    - expat                    # [linux]
    - libpng                   # [unix]
    - libtiff                  # [unix]
    - libtool                  # [linux]
    - freetype                 # [unix]
    - jpeg                     # [unix]
    - pango                    # [linux]
    - zlib                     # [unix]
    - libxcb                   # [linux]
    - xorg-libxau              # [linux]
    - xorg-libxrender          # [linux]
    - xorg-libxpm              # [linux]
    - gts                      # [not ppc64le and not aarch64]
    - gdk-pixbuf               # [unix]
    - gtk2                     # [unix]
    - libwebp                  # [unix]
  run:
    - cairo                    # [linux]
    - expat                    # [linux]
    - libpng                   # [unix]
    - libtiff                  # [unix]
    - libtool                  # [linux]
    - freetype                 # [unix]
    - jpeg                     # [unix]
    - pango                    # [unix]
    - zlib                     # [unix]
    - libxcb                   # [linux]
    - xorg-libxau              # [linux]
    - xorg-libxrender          # [linux]
    - xorg-libxpm              # [linux]
    - gts                      # [not ppc64le and not aarch64]
    - gdk-pixbuf               # [unix]
    - gtk2                     # [unix]
    - libwebp                  # [unix]
    - fonts-conda-ecosystem    # [unix]

test:
  commands:
    - dot -c
    - dot -V
    - fdp -V
    - neato -?  # [unix]
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]
  files:
    - sample.dot

about:
  home: http://www.graphviz.org/
  license: EPL-1.0
  license_family: Other
  license_file: COPYING
  summary: Open Source graph visualization software.
  description: |
    Graphviz is an open source graph visualization software. Graph visualization
    is a way of representing structural information as diagrams of abstract
    graphs and networks.
  doc_url: https://graphviz.gitlab.io/documentation/
  dev_url: https://gitlab.com/graphviz/graphviz/

extra:
  recipe-maintainers:
    - jakirkham
    - ccordoba12
    - ocefpaf
    - johanneskoester
