{% set version = "2.38.0" %}

package:
  name: graphviz
  version: {{ version }}

source:
  url: http://pkgs.fedoraproject.org/repo/pkgs/graphviz/graphviz-{{ version }}.tar.gz/5b6a829b2ac94efcd5fa3c223ed6d3ae/graphviz-{{ version }}.tar.gz  # [unix]
  md5: 5b6a829b2ac94efcd5fa3c223ed6d3ae  # [unix]

  url: https://graphviz.gitlab.io/_pages/Download/windows/graphviz-{{ version[:-2] }}.zip  # [win]
  md5: d028f49e047e2a25fdb7c0aa323a3945  # [win]

  patches:
    # This patch was submitted upstream:
    # http://www.graphviz.org/mantisbt/view.php?id=2448
    - gvconfig_libdir.patch  # [unix]

build:
  number: 8
  detect_binary_files_with_prefix: True  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config               # [osx]
  host:
    - cairo                    # [linux]
    - expat                    # [linux]
    - libpng                   # [unix]
    - libtiff                  # [unix]
    - libtool                  # [linux]
    - freetype                 # [unix]
    - jpeg                     # [unix]
    - pango                    # [linux]
    - zlib                     # [unix]
    - libxcb                   # [linux]
    - xorg-libxrender          # [linux]
    - xorg-libxpm              # [linux]
  run:
    - cairo                    # [linux]
    - expat                    # [linux]
    - libpng                   # [unix]
    - libtiff                  # [unix]
    - libtool                  # [linux]
    - freetype                 # [unix]
    - jpeg                     # [unix]
    - pango                    # [linux]
    - zlib                     # [unix]
    - libxcb                   # [linux]
    - xorg-libxrender          # [linux]
    - xorg-libxpm              # [linux]

test:
  commands:
    - dot -V
    - neato -?  # [unix]
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]
  files:
    - sample.dot

about:
  home: http://www.graphviz.org/
  license: EPL v1.0
  license_family: Other
  license_file: COPYING
  summary: Open Source graph visualization software.
  description: |
    Graphviz is an open source graph visualization software. Graph visualization
    is a way of representing structural information as diagrams of abstract
    graphs and networks.
  doc_url: http://www.graphviz.org/Documentation.php
  dev_url: https://github.com/ellson/graphviz

extra:
  recipe-maintainers:
    - jakirkham
    - ccordoba12
    - ocefpaf
    - johanneskoester
