{% set version = "13.1.2" %}

package:
  name: graphviz
  version: {{ version }}

source:
  - url: https://gitlab.com/graphviz/graphviz/-/archive/{{ version }}/graphviz-{{ version }}.tar.gz
    sha256: 0e79b8402e8ea13f05c0fc0e30604f1d0731cd3f60f85850cedac7e0ee420ef8
    patches:
      - patches/0001-Always-link-to-getopt-on-Windows.patch
      - patches/0002-Remove-requirement-of-hard-coded-DLLs-in-PATH.patch
      - patches/0003-Use-WebP-CMake-targets-instead-of-PkgConfig.patch
      - patches/0004-Fix-dependencies-for-gvplugin_gd.patch
      - patches/0005-Don-t-rely-on-pkgconfig-for-GTS-on-Windows.patch

    # Prefer header only compat layer, even though m2-libtool might work
  - url: https://gitlab.com/graphviz/graphviz-windows-dependencies/-/raw/c7eafb3c/x64/include/ltdl.h
    sha256: a3cf376bca2965634ba05926d4065a46331e71c487d84a4c6aceb795e9458bfd
    folder: ltdl_compat

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('graphviz', max_pin='x') }}
  # gkd-pixbuf -> libtiff -> liblzma (not a direct dep)
  ignore_run_exports:   # [unix]
    - liblzma                                             # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - pkg-config                                          # [unix]
    - make                                                # [unix]
    - bison                                               # [unix]
    - libtool                                             # [unix]
    - automake                                            # [unix]
    - autoconf                                            # [unix]
    - cmake                                               # [win]
    - ninja                                               # [win]
    - python >=3
    - m2-gawk                                             # [win]
    - m2-flex                                             # [win]
    - m2-bison                                            # [win]
    - perl                                                # [win]
    - pkgconf                                             # [win]
  host:
    # --with-pangocairo=yes
    - cairo
    # --with-expat=yes
    - expat
    # --with-gts=yes
    - gts
    # --with-gdk-pixbuf=yes
    - gdk-pixbuf                                          # [unix]
    # Only to satisfy pkg-config --cflags "gdk-pixbuf-2.0"
    - liblzma-devel                                       # [unix]
    # --with-gdk=yes
    - gtk3                                                # [unix]
    # pangocairo requires glib
    - glib
    - libglib
    # --with-libgd=yes
    - libgd
    # --with-rsvg=yes
    - librsvg                                             # [unix]
    # --with-webp=yes
    - libwebp-base
    # --with-pangocairo=yes
    - pango
    - xorg-xorgproto                                      # [unix]
    # default requirement
    - zlib
    # Windows only deps
    - getopt-win32                                        # [win]
  run:
    - fonts-conda-ecosystem                               # [unix]

test:
  files:
    - sample.dot

about:
  home: http://www.graphviz.org/
  license: EPL-1.0
  license_family: Other
  license_file: COPYING
  summary: Open Source graph visualization software.
  description: |
    Graphviz is an open source graph visualization software. Graph visualization
    is a way of representing structural information as diagrams of abstract
    graphs and networks.
  doc_url: https://graphviz.gitlab.io/documentation/
  dev_url: https://gitlab.com/graphviz/graphviz/

extra:
  recipe-maintainers:
    - jakirkham
    - ccordoba12
    - ocefpaf
    - johanneskoester
    - nehaljwani
